import type { SVGProps } from 'react';

/**
 * The site's logo: Animesh's signature. It is one shape drawn in `currentColor` (blue in light mode, white in
 * dark mode) from public/assets/brand/signature-sprite.svg. `weight` is a stroke in drawing units (the drawing is
 * 1000 wide) that thickens the hairlines; use a bigger one when the logo is small.
 * Generated by tools/make-brand-assets.mjs; do not edit by hand.
 */
export function Logo({ weight = 7, ...props }: SVGProps<SVGSVGElement> & { weight?: number }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="-12 -12 1024 378.18"
      fill="currentColor"
      stroke="currentColor"
      strokeWidth={weight}
      strokeLinejoin="round"
      strokeLinecap="round"
      {...props}
    >
      <use href="/assets/brand/signature-sprite.svg#signature" />
    </svg>
  );
}

/** Width divided by height of the logo, for sizing it. */
export const LOGO_ASPECT = 2.7077;
