import { portfolio } from './portfolio';

export type CuratedAnswer = {
  question: string;
  answer: string;
  /** Link on the source line and the "Learn more" button. */
  learn: string;
  /** Wording of the source line (defaults to "Source"). */
  learnSource?: string;
  learnLabel?: string;
  /** Primary button. */
  cta: string;
  url: string;
};

/**
 * The curated questions shown in the ⌘K palette. The palette shows them three at a time in the order of
 * `QUESTION_ORDER` (two pages), and each has a backdrop in public/assets/nous-web/composer/composer-<art>.webp.
 * These are fixed copy, not generated by an AI.
 */
export const answers: CuratedAnswer[] = [
  {
    question: 'What does Animesh work on?',
    answer:
      'NLP and ML evaluation, with a focus on scientific AI. His research asks when language models, and the measurements used to judge them, can be trusted when the underlying knowledge is heterogeneous, conflicting or uncertain: scientific retrieval, chemistry language models, translation metrics and LLM fairness auditing.',
    learn: '/releases',
    learnSource: 'Publications',
    cta: 'See publications',
    url: '/releases',
  },
  {
    question: 'Where has he published?',
    answer:
      'EMNLP 2026 Main (Beyond Epistemic Collapse: Disagreement-Aware Scientific Retrieval-Augmented Generation), WMT 2026 (Translation Metrics Cannot Judge What Their Tokeniser Deletes) and Digital Discovery, Royal Society of Chemistry (Notation matters: cross-representation inconsistency in chemistry language models and its mechanistic origins).',
    learn: portfolio.links.orcid,
    learnSource: 'ORCID',
    cta: 'See publications',
    url: '/releases',
  },
  {
    question: 'What is EVIRAG?',
    answer:
      'A disagreement-aware retrieval-augmented generation framework that stops language models collapsing conflicting scientific evidence into a single answer. EVIRAG-BENCH is a 1,250-query benchmark across five scientific domains, and it improves contradiction recall and viewpoint coverage over standard RAG.',
    learn: portfolio.links.evirag,
    learnSource: 'GitHub',
    learnLabel: 'View the code',
    cta: 'See publications',
    url: '/releases',
  },
  {
    question: 'Where has he worked?',
    answer:
      'He contributed to open-source work at Nous Research, researched at DRDO and Complexity Science Hub Vienna, and co-founded ClerkTree. He prefers fast, high-output environments over slow academic ones.',
    learn: '/careers',
    learnSource: 'Experience',
    learnLabel: 'See experience',
    cta: 'See experience',
    url: '/careers',
  },
  {
    question: 'What is he looking for next?',
    answer:
      'His next research role before a PhD. If you work in NLP, ML evaluation or AI research broadly, he is happy to connect and talk shop.',
    learn: portfolio.links.linkedin,
    learnSource: 'LinkedIn',
    learnLabel: 'Open LinkedIn',
    cta: 'Email Animesh',
    url: `mailto:${portfolio.email}`,
  },
  {
    question: 'How can I get in touch?',
    answer: 'Email works best. He is also on LinkedIn and GitHub, and the code for his papers is public.',
    learn: portfolio.links.github,
    learnSource: 'GitHub',
    learnLabel: 'Open GitHub',
    cta: 'Email Animesh',
    url: `mailto:${portfolio.email}`,
  },
];

/** Backdrop picture for each answer (same index as `answers`). */
export const ANSWER_ART = ['build', 'install', 'nous', 'models', 'private', 'contribute'] as const;

/** Order the questions appear in: indexes into `answers`, three per page. */
export const QUESTION_ORDER = [2, 0, 1, 3, 4, 5] as const;
export const QUESTIONS_PER_PAGE = 3;
export const QUESTION_PAGES = 2;
