// Compares the server-rendered HTML of the live site and the rebuild, element by element.
//
//   npx next start -p 3100 &
//   node tools/dom-diff.mjs                 # every page in the live sitemap
//   node tools/dom-diff.mjs /blog /releases # specific paths
//   SHOW=40 node tools/dom-diff.mjs /blog   # print up to 40 differing lines per page
//
// Both documents are normalized first (ids generated by React, ?v= cache-busters, asset hosts, attribute
// order, whitespace) so what remains are real differences in tags, classes, text and links.
import { parse } from 'parse5';
import { rewriteUrl } from './html-to-jsx.mjs';

const LOCAL = process.env.LOCAL ?? 'http://localhost:3100';
const LIVE = 'https://nousresearch.com';
const SHOW = Number(process.env.SHOW ?? 12);
const attr = (n, k) => (n.attrs || []).find((a) => a.name === k)?.value;
const SKIP = new Set(['script', 'style', 'link', 'meta', 'noscript', 'template', 'title']);

function normAttr(name, value, tag) {
  let v = value;
  if (/^_R_|^ui-\d+$/.test(v) || ['research-mobile-menu', 'home-composer', 'article-dock-list'].includes(v)) return '·';
  // intentional: the sign-off's /terms and /privacy 404 on the live site, so the rebuild links to the portal pages the footer uses
  if (name === 'href' && (v === '/terms' || v === '/privacy')) return `https://portal.nousresearch.com${v}`;
  if (['href', 'src', 'poster', 'content'].includes(name)) v = rewriteUrl(v);
  else if (name === 'srcset') v = v.split(',').map((p) => { const [u, ...r] = p.trim().split(/\s+/); return [rewriteUrl(u), ...r].join(' '); }).join(', ');
  if (name === 'class') v = v.split(/\s+/).filter(Boolean).sort().join(' ');
  if (name === 'style') v = v.replace(/https?:\/\/[^'")\s]+/g, (u) => rewriteUrl(u)).replace(/\s*([:;,])\s*/g, '$1').replace(/;$/, '');
  if (name === 'tabindex' || name === 'width' || name === 'height') v = String(Number(v));
  return v;
}

function lines(root) {
  const out = [];
  const walk = (n, depth) => {
    if (n.nodeName === '#text') { const t = n.value.replace(/\s+/g, ' ').trim(); if (t) out.push(`${' '.repeat(depth)}"${t}"`); return; }
    if (!n.tagName || SKIP.has(n.tagName)) return;
    const attrs = (n.attrs || [])
      .filter((a) => !['data-dpl-id', 'data-nimg'].includes(a.name) && !(['href', 'aria-label'].includes(a.name) && /nw-research-brand-link/.test(attr(n, 'class') || '')) && !(a.name === 'xmlns' && n.tagName === 'svg'))
      .map((a) => `${a.name}="${normAttr(a.name, a.value, n.tagName)}"`)
      .sort();
    if (n.tagName === 'div' && attrs.join('') === 'hidden=""' && !(n.childNodes || []).length) return; // Next portal anchor
    out.push(`${' '.repeat(depth)}<${n.tagName}${attrs.length ? ' ' + attrs.join(' ') : ''}>`);
    // intentional: on blog articles the rebuild renders the "Nous Blog" logo on the server (the original swaps it in after hydration)
    if ((attr(n, 'class') || '').split(' ').includes('nw-research-brand-link')) return;
    // merge adjacent text nodes (React inserts comment markers between them)
    const kids = [];
    for (const c of n.childNodes || []) {
      if (c.nodeName === '#comment') continue;
      const last = kids[kids.length - 1];
      if (c.nodeName === '#text' && last?.nodeName === '#text') kids[kids.length - 1] = { nodeName: '#text', value: last.value + c.value };
      else kids.push(c);
    }
    kids.forEach((c) => walk(c, depth + 1));
  };
  const body = (function find(n) { if (n.tagName === 'body') return n; for (const c of n.childNodes || []) { const r = find(c); if (r) return r; } })(root);
  walk(body, 0);
  return out;
}

function diffLines(a, b) {
  // longest-common-subsequence diff (pages are a few thousand lines)
  const n = a.length, m = b.length;
  const dp = Array.from({ length: n + 1 }, () => new Uint32Array(m + 1));
  for (let i = n - 1; i >= 0; i--) for (let j = m - 1; j >= 0; j--) dp[i][j] = a[i] === b[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1]);
  const res = []; let i = 0, j = 0;
  while (i < n && j < m) { if (a[i] === b[j]) { i++; j++; } else if (dp[i + 1][j] >= dp[i][j + 1]) res.push(`- ${a[i++].trim()}`); else res.push(`+ ${b[j++].trim()}`); }
  while (i < n) res.push(`- ${a[i++].trim()}`);
  while (j < m) res.push(`+ ${b[j++].trim()}`);
  return res;
}

let paths = process.argv.slice(2);
if (!paths.length) {
  const xml = await (await fetch(`${LIVE}/sitemap.xml`)).text();
  paths = [...xml.matchAll(/<loc>https:\/\/nousresearch\.com([^<]*)/g)].map((m) => m[1] || '/');
}
let bad = 0;
for (const p of paths) {
  const [live, local] = await Promise.all([fetch(LIVE + p), fetch(LOCAL + p)]);
  const a = lines(parse(await live.text())), b = lines(parse(await local.text()));
  if (process.env.DUMP) { const fs = await import('node:fs'); fs.mkdirSync('.compare', { recursive: true }); fs.writeFileSync('.compare/dom-live.txt', a.join('\n')); fs.writeFileSync('.compare/dom-local.txt', b.join('\n')); }
  const d = diffLines(a, b);
  if (d.length) bad++;
  console.log(`${d.length ? 'DIFF' : 'SAME'} ${p}  (${a.length} / ${b.length} nodes, ${d.length} differing lines)`);
  for (const l of d.slice(0, SHOW)) console.log('   ' + l.slice(0, 230));
}
console.log(`\n${paths.length - bad}/${paths.length} pages identical`);
process.exitCode = bad ? 1 : 0;
