"""Obscures the two background portraits on the poster (the left and right panels), keeping the centre
portrait sharp. Each panel is blurred hard and covered with a halftone dot screen, the same dithered look
as the site's other artwork, with feathered edges so it melts into the paper.

    python3 tools/obscure-poster.py            # original (tools/assets) -> public/assets/portfolio/
Needs Pillow. Edit PANELS if the poster changes; boxes are (left, top, right, bottom) in source pixels.
"""
from PIL import Image, ImageDraw, ImageFilter, ImageChops, ImageStat, ImageOps
import os

SRC = os.path.join(os.path.dirname(__file__), 'assets', 'animesh-mishra-poster.original.webp')
OUT = os.path.join(os.path.dirname(__file__), '..', 'public', 'assets', 'portfolio', 'animesh-mishra-poster.webp')
PANELS = [(2, 362, 232, 908), (1014, 370, 1254, 906)]
BLUR = 15      # how smeared the faces become
CELL = 6       # halftone dot pitch, in pixels
FEATHER = 5    # soft edge between obscured area and paper
# The printed label under the role line is cloned out with clean paper from just below it.
CLONE_OUT = [((568, 1038, 668, 1086), (568, 1096, 668, 1144))]  # (area to hide, clean paper to copy over it)


def halftone(gray, cell):
    """Dots on a grid, radius growing with darkness: the screen-print look."""
    w, h = gray.size
    small = gray.resize((max(1, w // cell), max(1, h // cell)), Image.BILINEAR)
    S = 4  # supersample for round dots
    canvas = Image.new('L', (w * S, h * S), 255)
    d = ImageDraw.Draw(canvas)
    px = small.load()
    for cy in range(small.size[1]):
        for cx in range(small.size[0]):
            dark = 1 - px[cx, cy] / 255
            r = (cell * 0.72) * (dark ** 0.8) * S
            if r < 0.6:
                continue
            x, y = (cx + 0.5) * cell * S, (cy + 0.5) * cell * S
            d.ellipse((x - r, y - r, x + r, y + r), fill=0)
    return canvas.resize((w, h), Image.LANCZOS)


im = Image.open(SRC).convert('RGB')
for (l, t, r, b) in PANELS:
    box = (l, t, r, b)
    region = im.crop(box)
    blurred = region.filter(ImageFilter.GaussianBlur(BLUR))
    # flatten the contrast a little so the figure reads as a smudge, not a face
    mean = ImageStat.Stat(blurred.convert('L')).mean[0]
    gray = blurred.convert('L').point(lambda v: int(mean + (v - mean) * 1.25))
    dots = halftone(gray, CELL)
    paper = Image.new('L', region.size, 232)
    screen = ImageChops.multiply(paper, dots.point(lambda v: 70 + int(v * 185 / 255)))  # dots at ~75% ink
    # mix: mostly the blur (keeps the tone) with the dot screen on top
    base = blurred.convert('L')
    mixed = ImageChops.blend(base, screen, 0.7)
    tint = Image.merge('RGB', (mixed, mixed, mixed))
    mask = Image.new('L', region.size, 0)
    ImageDraw.Draw(mask).rectangle((FEATHER, FEATHER, region.size[0] - FEATHER, region.size[1] - FEATHER), fill=255)
    mask = mask.filter(ImageFilter.GaussianBlur(FEATHER / 1.5))
    im.paste(tint, (l, t), mask)

for (l, t, r, b), (sl, st, sr, sb) in CLONE_OUT:
    patch = im.crop((sl, st, sr, sb))
    mask = Image.new('L', patch.size, 0)
    ImageDraw.Draw(mask).rectangle((2, 2, patch.size[0] - 2, patch.size[1] - 2), fill=255)
    im.paste(patch, (l, t), mask.filter(ImageFilter.GaussianBlur(1.5)))

# Warm duotone in the site palette (Cherry Cola / Cream Vanilla family): near-black ink on cream paper.
im = ImageOps.colorize(ImageOps.autocontrast(im.convert('L'), cutoff=0.5), black='#1c0a0a', white='#f6eee6')

os.makedirs(os.path.dirname(OUT), exist_ok=True)
im.save(OUT, 'WEBP', quality=90, method=6)
print('wrote', os.path.relpath(OUT))


# --- Edge colours --------------------------------------------------------------------------------
# On wide screens the whole (square) poster is shown and the space beside it is filled with the poster's
# own paper colour, taken row by row from its left and right edges, so the join is invisible.
# Written to styles/poster-edges.css.
def edge_gradient(img, x0, x1, bands=24):
    w, h = img.size
    stops = []
    for i in range(bands + 1):
        y = min(h - 1, int(i * (h - 1) / bands))
        box = (x0, max(0, y - h // (bands * 2)), x1, min(h, y + h // (bands * 2) + 1))
        r, g, b = ImageStat.Stat(img.crop(box)).mean[:3]
        stops.append(f'rgb({round(r)} {round(g)} {round(b)}) {round(100 * i / bands, 1)}%')
    return 'linear-gradient(to bottom, ' + ', '.join(stops) + ')'

final = im
css = (
    '/* Generated by tools/obscure-poster.py: the poster\'s edge colours, used beside it on wide screens. */\n'
    '.pf-poster {\n'
    f'  --pf-edge-left: {edge_gradient(final, 0, 24)};\n'
    f'  --pf-edge-right: {edge_gradient(final, final.size[0] - 24, final.size[0])};\n'
    '}\n'
)
open(os.path.join(os.path.dirname(__file__), '..', 'styles', 'poster-edges.css'), 'w').write(css)
print('wrote styles/poster-edges.css')
